from functools import lru_cache
from pathlib import Path
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    service_name: str = "feishu-agent-runtime"
    environment: str = "production"
    host: str = "0.0.0.0"
    port: int = 8080

    runtime_config_path: Path = Field(
        default=Path("/app/config/agent-runtime-config.json"),
        description="Path to agent-runtime-config.json generated by build-runtime-config.py.",
    )
    data_dir: Path = Path("/app/data")
    database_path: Path | None = None

    channel_auth_token: str = Field(
        default="",
        description="Shared bearer token required from the Channel SDK adapter.",
    )

    openai_api_key: str = ""
    openai_base_url: str = "https://api.openai.com/v1"
    openai_model: str = "gpt-4.1-mini"
    openai_timeout_seconds: float = 90.0
    openai_max_retries: int = 2
    openai_retry_backoff_seconds: float = 1.0
    max_context_messages: int = 24

    @property
    def resolved_database_path(self) -> Path:
        if self.database_path is not None:
            return self.database_path
        return self.data_dir / "runtime.sqlite3"


@lru_cache
def get_settings() -> Settings:
    return Settings()
